name: Firebase Deploy (rules)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Firestore & Storage Rules
        uses: w9jds/firebase-action@v13.4.1
        with:
          args: deploy --only firestore:rules,storage:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: studio-3733247372-de271
